// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDGfS-UyngOJKRYZDgSVMxc-DCEvLiues',
    appId: '1:273199609264:web:120e551af7c12af77bd275',
    messagingSenderId: '273199609264',
    projectId: 'adsapp-5013e',
    authDomain: 'adsapp-5013e.firebaseapp.com',
    storageBucket: 'adsapp-5013e.appspot.com',
    measurementId: 'G-FYT1QHLNEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6S-LUxWJBfP5Fme2KjjSIrnRk6EQwoI',
    appId: '1:273199609264:android:9361dbf79d0a8f0e7bd275',
    messagingSenderId: '273199609264',
    projectId: 'adsapp-5013e',
    storageBucket: 'adsapp-5013e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeexkw6_STq9XKDfDVH7ghVnRd-pZYNMc',
    appId: '1:273199609264:ios:6c47eb97af1270507bd275',
    messagingSenderId: '273199609264',
    projectId: 'adsapp-5013e',
    storageBucket: 'adsapp-5013e.appspot.com',
    iosBundleId: 'com.platsafqat.ahgh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeexkw6_STq9XKDfDVH7ghVnRd-pZYNMc',
    appId: '1:273199609264:ios:6c47eb97af1270507bd275',
    messagingSenderId: '273199609264',
    projectId: 'adsapp-5013e',
    storageBucket: 'adsapp-5013e.appspot.com',
    iosBundleId: 'com.platsafqat.ahgh',
  );
}
